name: streakit
description: A new Flutter project.
publish_to: "none"
version: 0.1.2+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  animated_custom_dropdown: ^3.1.1
  awesome_notifications: ^0.10.1
  brick_core: ^1.2.1
  brick_offline_first_with_supabase: ^1.1.2
  brick_sqlite: ^3.1.1+1
  brick_supabase: ^1.1.3
  crystal_navigation_bar: ^1.0.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.2.0
  firebase_analytics: ^11.4.1
  firebase_core: ^3.10.1
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter
  flutter_heatmap_calendar:
    path: ./flutter_heatmap_calendar
  flutter_html: ^3.0.0-beta.2
  flutter_iconly: ^1.0.2
  flutter_onboarding_slider: ^1.0.11
  flutter_otp_text_field: ^1.2.0
  flutter_popup: ^3.3.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  intl: ^0.20.2
  lottie: ^3.3.0
  package_info_plus: ^8.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4+6
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  supabase_flutter: ^2.8.2
  table_calendar: ^3.1.2
  toasty_box: ^1.0.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  brick_offline_first_with_supabase_build: ^1.0.0
  build_runner: ^2.4.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/gifs/
    - assets/icon_pack/
    - assets/lottie/
    - assets/logo/
